### ISSUE TITLE
H96 MAX V58 

### ISSUE THREAD

**Issue by manaboy** [edk2-porting/edk2-rk3588#137]
Is the H96 max v58 which the original manufacturer has released final firmware with release keys going to be supported by this custom firmware?

**Comment by Googulator** [comment]
While I'm not familiar with the specifics of the H96 Max, do note that this project isn't "firmware" in the same sense it's usually understood in relation to TV boxes, i.e. not a custom or modified operating system image. Instead, it's a UEFI-compatible SPI boot image (similar to what's called a bootloader in TV box parlance) that enables loading generic, general-purpose operating systems intended for ARM SystemReady and similar systems.

**Comment by manaboy** [comment]
Would that include bootloading windows or Linux in that manner?

**Comment by el-bakkali** [comment]
I own this box, so I went ahead and ported it — @mariobalanica, you mentioned contributions were welcome, so here it is: #270.

It builds, flashes and boots on real hardware. Verified working: UEFI front page, HDMI0 output, Gigabit Ethernet (GMAC1 + RTL8211F, PXE over both IPv4 and IPv6), USB boot and HID, eMMC, and 8192 MB RAM correctly reported.

**Two things do not work, and I would appreciate help from anyone with the same box:**

- **Wi-Fi.** The module is on `pcie2x1l0` and shows up as `14e4:449d` under the stock Android kernel. I drive `pcie_3v3` from GPIO4_PA1 in `PciePowerEn`, but the adapter still does not come up under Linux. A third-party report calls it an AP6275P / BCM43752; I have not independently confirmed the part.
- **Audio.** No output at all. The vendor DT has an ES8311 codec at `0x18` on i2c3, which the mainline DT for this board does not describe.

I would rather submit the port with both honestly marked than sit on it.

**On the OS side:** the only thing I have successfully installed so far is **Fedora Workstation 44**, onto the internal eMMC, in mainline device tree mode. The important part is that it was done with *manual* partitioning so the firmware's `uboot` partition stayed intact — if you let an installer "erase disk and install", it rewrites the GPT from sector 0 and takes both `uboot` and the IDBlock with it.

@manaboy — two warnings specific to this box, since it is a TV box rather than a dev board:

1. **There is no SPI NOR flash and no microSD slot.** `mmc@fe2c0000` is enabled in the Rockchip reference DT the vendor started from, so the boot log will claim it probed an SD controller, but no slot is physically fitted. The firmware therefore has to go on eMMC, and every flash overwrites the stock bootloader. There is no removable-media escape hatch. Recovery is the maskrom pinhole inside the AV/optical jack, which works reliably.
2. **Back up stock Android before you flash anything.** There is no vendor firmware download for this box, so the only route back is a dump you take yourself while it is still stock — and the partition people forget is `super` (3112 MiB), which holds system/vendor/product under dynamic partitions. Without it there is nothing to restore. `userdata` can be skipped since a restore wipes it anyway, which keeps the backup at roughly 4 GiB. I have since restored my box to stock Android from exactly that backup and verified it by SHA-256 read-back, so it is genuinely reversible — but only if the dump exists first.

Full hardware discovery, cold-boot serial logs, the decompiled vendor device tree, the PMIC/GPIO inventory and the backup/restore procedure are written up at <https://github.com/el-bakkali/h96-max-v58-hardware>.
